/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timeManager;

import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.client.FindIterable;
import java.awt.Window;
import java.beans.Statement;
import java.net.UnknownHostException;
import java.sql.ResultSet;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Document;

/**
 *
 * @author NK
 */
public class View_Employee_UI extends javax.swing.JPanel {

            String eID = null;
            String employee_Name = null;
            String faculty = null;
            String department = null;
            String centre = null;
            String building = null;
            String occupation = null;
    /**
     * Creates new form View_Employee_UI
     */
    public View_Employee_UI() {
        initComponents();
        
        DB edb = null;
        DBCollection col = null;
        
         //retrive data
        try{
            edb = DBManager.getDatabase();
        }catch(UnknownHostException e){
            JOptionPane.showMessageDialog(null, "Error Connecting To DB");
        }   
        col = edb.getCollection("Employee");
        DBObject resultdb = col.findOne();
        System.out.println(resultdb.get("Employee ID"));
    
        if( resultdb != null){
             eID = (String)resultdb.get("Employee ID");
             employee_Name = (String)resultdb.get("Employee_Name");
             faculty = (String)resultdb.get("Faculty");
             department = (String)resultdb.get("Department");
             centre = (String)resultdb.get("Center");
             building = (String)resultdb.get("Building");
             occupation = (String)resultdb.get("Occupation");
             
             //System.out.println(eID+""+employee_Name+""+faculty+""+department+""+centre+""+building+""+occupation);
        }
        String[] columNames = {"Employee ID","Employee Name","Employee Faculty","Department","Center","Building","Occupation"};
         DefaultTableModel dtm = new DefaultTableModel(columNames,0);
        
//            dtm.addColumn("Employee ID");
//            dtm.addColumn("Employee Name");
//            dtm.addColumn("Employee Faculty");
//            dtm.addColumn("Department");
//            dtm.addColumn("Center");
//            dtm.addColumn("Building");
//            dtm.addColumn("Occupation");
            
            String Query = "SELECT * FROM Employee";
            
            
            try {
            
        } catch (Exception e) {
        }
//        //loop through records
//        
                DBCursor iterDoc = col.find();
//                
//   // Getting the iterator 
//   Iterator i = iterDoc.iterator(); 
//
//                
//                while(iterDoc.hasNext()){
//                    //System.out.println(iterDoc.next());
//                    dtm.addRow(new String[]{eID,employee_Name,faculty,department,centre,building,occupation});
//
//              
//                }            
//  jTable1.setModel(dtm);
  
      while(iterDoc.hasNext()) {
        DBObject obj = iterDoc.next();
             eID = (String)obj.get("Employee ID");
             employee_Name = (String)obj.get("Employee_Name");
             faculty = (String)obj.get("Faculty");
             department = (String)obj.get("Department");
             centre = (String)obj.get("Center");
             building = (String)obj.get("Building");
             occupation = (String)obj.get("Occupation");  
        dtm.addRow(new String[]{eID,employee_Name,faculty,department,centre,building,occupation});

    }
    jTable1.setModel(dtm);
  
  
  
  
  
  
  
  
  
  
  
  
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("View Employee");

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Search");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(177, 177, 177)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 220, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Dashboard b=new Dashboard();
        b.setVisible(true);
        JPanel comp = (JPanel) evt.getSource();
        Window win = SwingUtilities.getWindowAncestor(comp);
        win.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
