/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timeManage;

import com.mongodb.BasicDBObject;
import com.mongodb.BasicDBObjectBuilder;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBObject;
import com.mongodb.WriteResult;
import java.net.UnknownHostException;
import java.time.LocalTime;
import javax.swing.JOptionPane;
import org.bson.conversions.Bson;

/**
 *
 * @author Thisura
 */
public class Settings extends javax.swing.JPanel {

    /**
     * Creates new form Settings
     */
    int numberOfWorkingDays = 0;
    DB SettingDB = null;
    DBCollection col=null;
    
    public Settings() {
        initComponents();
        
        
        try
        {
        SettingDB = DBManager.getDatabase();
        }
        catch (UnknownHostException ex)
        {
        JOptionPane.showMessageDialog(null, "Error When Connecting to DB");
        }
        col = SettingDB.getCollection("Setting");
        
        DBObject settingsObject= col.findOne();
        
       if(settingsObject != null){
        
            numberOfWorkingDays = (Integer)settingsObject.get("NoOfWorkingDays");
            txt_no_of_wrkng_days_p_week.setText(Integer.toString(numberOfWorkingDays));
            timePicker_starting_time.setText(settingsObject.get("StartTime").toString());

            String wrkngDays = settingsObject.get("WorkingDays").toString();

            if(wrkngDays.matches("(.*)MONDAY(.*)")){
                jCheckBox_monday.setSelected(true);
            }
            if(wrkngDays.matches("(.*)TUESDAY(.*)")){
                jCheckBox_tuesday.setSelected(true);
            }
            if(wrkngDays.matches("(.*)WEDNSDAY(.*)")){
                jCheckBox_wednsday.setSelected(true);
            }
            if(wrkngDays.matches("(.*)THURSDAY(.*)")){
                jCheckBox_thursday.setSelected(true);
            }
            if(wrkngDays.matches("(.*)FRIDAY(.*)")){
                jCheckBox_friday.setSelected(true);
            }
            if(wrkngDays.matches("(.*)SATURDAY(.*)")){
                jCheckBox_saturday.setSelected(true);
            }
            if(wrkngDays.matches("(.*)SUNDAY(.*)")){
                jCheckBox_sunday.setSelected(true);
            }

            String timeslot = settingsObject.get("TimeSlot").toString();
            System.out.println();
            if(timeslot.equals("ONE_HOUR") ){
                jRadioButton_time_slots_1hr.setSelected(true);
            }
            if(timeslot.equals("30_MINUTES")){
                jRadioButton_time_slot_30min.setSelected(true);
            }
            else{
                jRadioButton_time_slots_1hr.setSelected(true);
            }
            jComboBox1.setSelectedItem(settingsObject.get("WorkingTimePerDay"));
       }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox_sunday = new javax.swing.JCheckBox();
        jCheckBox_monday = new javax.swing.JCheckBox();
        jCheckBox_tuesday = new javax.swing.JCheckBox();
        jCheckBox_wednsday = new javax.swing.JCheckBox();
        jCheckBox_thursday = new javax.swing.JCheckBox();
        jCheckBox_friday = new javax.swing.JCheckBox();
        jCheckBox_saturday = new javax.swing.JCheckBox();
        txt_no_of_wrkng_days_p_week = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton_time_slots_1hr = new javax.swing.JRadioButton();
        jRadioButton_time_slot_30min = new javax.swing.JRadioButton();
        timePicker_starting_time = new com.github.lgooddatepicker.components.TimePicker();
        btn_save = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        jLabel1.setText("SETTINGS");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel2.setText("Working Days");
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jCheckBox_sunday.setText("Sunday");
        jCheckBox_sunday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_sunday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_sundayActionPerformed(evt);
            }
        });

        jCheckBox_monday.setText("Monday");
        jCheckBox_monday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_monday.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox_mondayStateChanged(evt);
            }
        });
        jCheckBox_monday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_mondayActionPerformed(evt);
            }
        });

        jCheckBox_tuesday.setText("Tuesday");
        jCheckBox_tuesday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_tuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_tuesdayActionPerformed(evt);
            }
        });

        jCheckBox_wednsday.setText("Wednsday");
        jCheckBox_wednsday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_wednsday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_wednsdayActionPerformed(evt);
            }
        });

        jCheckBox_thursday.setText("Thursday");
        jCheckBox_thursday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_thursday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_thursdayActionPerformed(evt);
            }
        });

        jCheckBox_friday.setText("Friday");
        jCheckBox_friday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_friday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_fridayActionPerformed(evt);
            }
        });

        jCheckBox_saturday.setText("Saturday");
        jCheckBox_saturday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_saturday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_saturdayActionPerformed(evt);
            }
        });

        txt_no_of_wrkng_days_p_week.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_no_of_wrkng_days_p_week.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_no_of_wrkng_days_p_weekActionPerformed(evt);
            }
        });

        jLabel3.setText("Number of Working Days Per Week");
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setText("Working Time Per Day");
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setText("Time Slots");
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setText("Starting Time");
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jRadioButton_time_slots_1hr.setText("One Hour");
        jRadioButton_time_slots_1hr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton_time_slots_1hr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_time_slots_1hrActionPerformed(evt);
            }
        });

        jRadioButton_time_slot_30min.setText("30Minutes");
        jRadioButton_time_slot_30min.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton_time_slot_30min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_time_slot_30minActionPerformed(evt);
            }
        });

        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        jLabel7.setText("hrs");
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "05:00", "05:30", "06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_no_of_wrkng_days_p_week, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox_thursday)
                                            .addComponent(jCheckBox_sunday)
                                            .addComponent(jCheckBox_wednsday)
                                            .addComponent(jCheckBox_monday)
                                            .addComponent(jCheckBox_tuesday)
                                            .addComponent(jCheckBox_friday)
                                            .addComponent(jCheckBox_saturday))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(timePicker_starting_time, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(57, 57, 57))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel5)
                                                            .addComponent(jLabel4))
                                                        .addGap(27, 27, 27)
                                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel7)))
                                                .addGap(44, 44, 44))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButton_time_slots_1hr)
                                                    .addComponent(jRadioButton_time_slot_30min))
                                                .addGap(152, 152, 152))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_save)))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)
                        .addComponent(jCheckBox_sunday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox_monday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox_tuesday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox_wednsday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox_thursday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox_friday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox_saturday)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_no_of_wrkng_days_p_week, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_time_slots_1hr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_time_slot_30min)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(timePicker_starting_time, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btn_save)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_sundayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_sundayActionPerformed
        if(jCheckBox_sunday.isSelected()){
            String noOfWrkngDys = Integer.toString(++numberOfWorkingDays);
            txt_no_of_wrkng_days_p_week.setText(noOfWrkngDys);
        }else{
            String noOfWrkngDys = Integer.toString(--numberOfWorkingDays);
            txt_no_of_wrkng_days_p_week.setText(noOfWrkngDys);
        }
    }//GEN-LAST:event_jCheckBox_sundayActionPerformed

    private void jRadioButton_time_slots_1hrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_time_slots_1hrActionPerformed
        
        jRadioButton_time_slots_1hr.setSelected(true);
        jRadioButton_time_slot_30min.setSelected(false);
    }//GEN-LAST:event_jRadioButton_time_slots_1hrActionPerformed

    private static DBObject createDBObject(Setting setting_)
{
            BasicDBObjectBuilder docBuilder = BasicDBObjectBuilder.start();
            docBuilder.append("SettingId", setting_.getSettingid());
            docBuilder.append("NoOfWorkingDays", setting_.getNoOfWorkingDays());
            docBuilder.append("WorkingDays", setting_.getWorkingDays());
            docBuilder.append("StartTime", setting_.getStartingTime());
            docBuilder.append("TimeSlot", setting_.getTimeSlot());
            docBuilder.append("WorkingTimePerDay", setting_.getWorkingTimePerDay());
             return docBuilder.get();
}
    
    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed

        String[] workingDays = new String[7];
        int i=0;
        if(jCheckBox_sunday.isSelected()){
            workingDays[i++] = "SUNDAY";
        }
        if(jCheckBox_monday.isSelected()){
            workingDays[i++] = "MONDAY";
        }
        if(jCheckBox_tuesday.isSelected()){
            workingDays[i++] = "TUESDAY";
        }
        if(jCheckBox_wednsday.isSelected()){
            workingDays[i++] = "WEDNSDAY";
        }
        if(jCheckBox_thursday.isSelected()){
            workingDays[i++] = "THURSDAY";
        }
        if(jCheckBox_friday.isSelected()){
            workingDays[i++] = "FRIDAY";
        }
        if(jCheckBox_saturday.isSelected()){
            workingDays[i++] = "SATURDAY";
        }
        
        String workingTimePerDay = jComboBox1.getSelectedItem().toString();
        
        String timeSlot="";
        if(jRadioButton_time_slots_1hr.isSelected()){
            timeSlot = "ONE_HOUR";
        }
        else if(jRadioButton_time_slot_30min.isSelected()){
            timeSlot = "30_MINUTES";
        }
        
        String startTime = timePicker_starting_time.getTime().toString();
        if(numberOfWorkingDays>0){
            try {
            Setting setting = new Setting(1,numberOfWorkingDays,workingDays,startTime,timeSlot,workingTimePerDay);
            DBObject doc = createDBObject(setting);

            BasicDBObject searchQuery = new BasicDBObject().append("SettingId", 1);
            WriteResult updateResult = col.update(searchQuery,doc);
//            WriteResult updateResult = col.insert(doc);
           
            } catch (Exception e) {
                System.out.println(e);
                Notification notification = new Notification("Error when updating");
                notification.setLocation(600, 400);
                notification.setVisible(true);
            }
            
            Notification notification = new Notification("Successfully Updated");
            notification.setLocation(600, 400);
            notification.setVisible(true);
        }else{
            Notification notification = new Notification("Please Select working days");
            notification.setLocation(600, 400);
            notification.setVisible(true);
        }
        
    }//GEN-LAST:event_btn_saveActionPerformed

    private void txt_no_of_wrkng_days_p_weekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_no_of_wrkng_days_p_weekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_no_of_wrkng_days_p_weekActionPerformed

    private void jCheckBox_mondayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox_mondayStateChanged
       
    }//GEN-LAST:event_jCheckBox_mondayStateChanged

    private void jCheckBox_mondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_mondayActionPerformed
        if(jCheckBox_monday.isSelected()){
            String noOfWrkngDys = Integer.toString(++numberOfWorkingDays);
            txt_no_of_wrkng_days_p_week.setText(noOfWrkngDys);
        }else{
            String noOfWrkngDys = Integer.toString(--numberOfWorkingDays);
            txt_no_of_wrkng_days_p_week.setText(noOfWrkngDys);
        }
    }//GEN-LAST:event_jCheckBox_mondayActionPerformed

    private void jCheckBox_tuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_tuesdayActionPerformed
        if(jCheckBox_tuesday.isSelected()){
            String noOfWrkngDys = Integer.toString(++numberOfWorkingDays);
            txt_no_of_wrkng_days_p_week.setText(noOfWrkngDys);
        }else{
            String noOfWrkngDys = Integer.toString(--numberOfWorkingDays);
            txt_no_of_wrkng_days_p_week.setText(noOfWrkngDys);
        }
    }//GEN-LAST:event_jCheckBox_tuesdayActionPerformed

    private void jCheckBox_wednsdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_wednsdayActionPerformed
        if(jCheckBox_wednsday.isSelected()){
            String noOfWrkngDys = Integer.toString(++numberOfWorkingDays);
            txt_no_of_wrkng_days_p_week.setText(noOfWrkngDys);
        }else{
            String noOfWrkngDys = Integer.toString(--numberOfWorkingDays);
            txt_no_of_wrkng_days_p_week.setText(noOfWrkngDys);
        }
    }//GEN-LAST:event_jCheckBox_wednsdayActionPerformed

    private void jCheckBox_thursdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_thursdayActionPerformed
        if(jCheckBox_thursday.isSelected()){
            String noOfWrkngDys = Integer.toString(++numberOfWorkingDays);
            txt_no_of_wrkng_days_p_week.setText(noOfWrkngDys);
        }else{
            String noOfWrkngDys = Integer.toString(--numberOfWorkingDays);
            txt_no_of_wrkng_days_p_week.setText(noOfWrkngDys);
        }
    }//GEN-LAST:event_jCheckBox_thursdayActionPerformed

    private void jCheckBox_fridayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_fridayActionPerformed
        if(jCheckBox_friday.isSelected()){
            String noOfWrkngDys = Integer.toString(++numberOfWorkingDays);
            txt_no_of_wrkng_days_p_week.setText(noOfWrkngDys);
        }else{
            String noOfWrkngDys = Integer.toString(--numberOfWorkingDays);
            txt_no_of_wrkng_days_p_week.setText(noOfWrkngDys);
        }
    }//GEN-LAST:event_jCheckBox_fridayActionPerformed

    private void jCheckBox_saturdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_saturdayActionPerformed
        if(jCheckBox_saturday.isSelected()){
            String noOfWrkngDys = Integer.toString(++numberOfWorkingDays);
            txt_no_of_wrkng_days_p_week.setText(noOfWrkngDys);
        }else{
            String noOfWrkngDys = Integer.toString(--numberOfWorkingDays);
            txt_no_of_wrkng_days_p_week.setText(noOfWrkngDys);
        }
    }//GEN-LAST:event_jCheckBox_saturdayActionPerformed

    private void jRadioButton_time_slot_30minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_time_slot_30minActionPerformed
        jRadioButton_time_slots_1hr.setSelected(false);
        jRadioButton_time_slot_30min.setSelected(true);
    }//GEN-LAST:event_jRadioButton_time_slot_30minActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_save;
    private javax.swing.JCheckBox jCheckBox_friday;
    private javax.swing.JCheckBox jCheckBox_monday;
    private javax.swing.JCheckBox jCheckBox_saturday;
    private javax.swing.JCheckBox jCheckBox_sunday;
    private javax.swing.JCheckBox jCheckBox_thursday;
    private javax.swing.JCheckBox jCheckBox_tuesday;
    private javax.swing.JCheckBox jCheckBox_wednsday;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton_time_slot_30min;
    private javax.swing.JRadioButton jRadioButton_time_slots_1hr;
    private com.github.lgooddatepicker.components.TimePicker timePicker_starting_time;
    private javax.swing.JTextField txt_no_of_wrkng_days_p_week;
    // End of variables declaration//GEN-END:variables
}
